<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Db\ApplicationSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Event
 *
 * Structure class for relation application.event.
 * Event
 *
 *
 *
 * @see RowStructure
 */
class Event extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('application.event')
            ->setPrimaryKey(['event_id'])
            ->addField('event_id', 'int4')
            ->addField('created_at', 'timestamp')
            ->addField('updated_at', 'timestamp')
            ->addField('name', 'public.hstore')
            ->addField('enabled', 'bool')
            ->addField('characteristic', 'jsonb')
            ->addField('timespan', 'tsrange')
            ->addField('category_id', 'int4')
            ->addField('coordinates', 'point')
            ;
    }
}
